stages:
  - build

maven:
  stage: build
  image:
    name: maven:3.6-openjdk-8
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  script:
    - mvn clean install -DskipTests
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/dependency-check-report.html
    expire_in: 30 min
